language: node_js

node_js:
  - 4
  - 5

script:
  - npm run depcheck
  - npm run depcheck-web
  - npm run build
  - npm run test-coverage
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

deploy:
  provider: azure_web_apps
  on:
    tags: true
    node: 5

before_deploy:
  - git checkout -b master

after_deploy:
  - curl https://depcheck.tk
