language: node_js

node_js:
  - 'node'

script:
  - npm run depcheck -- --web-report
  - npm run build
  - npm run test-coverage
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

before_deploy:
  - ./node_modules/.bin/patch-version

deploy:
  provider: azure_web_apps
  on:
    tags: true
